baseURL = "https://joelhgil.github.io/"
languageCode = "es-ar"
title = "Nevar Studio"
theme = "PaperMod"
publishDir = "docs"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Manifiesto"
    url = "/posts/manifiesto/"
    weight = 2

  [[menu.main]]
    name = "Casos"
    url = "/posts/casos/"
    weight = 3

  [[menu.main]]
    name = "Contacto"
    url = "/posts/contacto/"
    weight = 4
